-- DDL for item-related tables (Metro schema)
-- Run this manually on the metro database
-- These match the SQL generated by MetroIntegrationService

-- Drop old incorrect tables if they exist
DROP TABLE IF EXISTS questionnaire_items;
DROP TABLE IF EXISTS competence_items;
DROP TABLE IF EXISTS item_translations;
DROP TABLE IF EXISTS items;

-- Items table
CREATE TABLE items (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    invertOrder TINYINT DEFAULT 0
);

-- Item translations (leftText = Niet-vraag, rightText = Wel-vraag)
CREATE TABLE item_translations (
    itemId BIGINT NOT NULL,
    language VARCHAR(5) NOT NULL,
    leftText TEXT,
    rightText TEXT,
    PRIMARY KEY (itemId, language),
    FOREIGN KEY (itemId) REFERENCES items(id) ON DELETE CASCADE
);

-- Competence to item mapping
CREATE TABLE competence_items (
    competenceId BIGINT NOT NULL,
    itemId BIGINT NOT NULL,
    PRIMARY KEY (competenceId, itemId),
    FOREIGN KEY (itemId) REFERENCES items(id) ON DELETE CASCADE
);

-- Questionnaire to item mapping with order
CREATE TABLE questionnaire_items (
    questionnaireId BIGINT NOT NULL,
    itemId BIGINT NOT NULL,
    `order` INT NOT NULL,
    PRIMARY KEY (questionnaireId, itemId),
    FOREIGN KEY (itemId) REFERENCES items(id) ON DELETE CASCADE
);
